
name: Backtest via Web Ingest (final)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "15 06 * * *"

jobs:
  backtest-all:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: etf-trading-engine
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: python -m pip install -r etf-trading-engine/requirements.txt pyyaml

      - name: Download EOD from Yahoo
        run: |
          python etf-trading-engine/scripts/download_eod_yf.py             --universe etf-trading-config/universe.csv             --output etf-trading-engine/data/eod.csv             --start 2018-01-01             --threads 1             --sleep 1             --min_success 2

      - name: Sanity check
        run: python etf-trading-engine/scripts/sanity_check.py --data etf-trading-engine/data/eod.csv

      - name: Ensure required params (top-level and per-run)
        run: |
          python - << 'PY'
          import yaml, os, sys
          p="etf-trading-config/model.yaml"
          with open(p,"r",encoding="utf-8") as f:
              cfg=yaml.safe_load(f) or {}
          # ensure top-level
          cfg.setdefault("params",{})
          cfg["params"].setdefault("atr_pct",1.0)
          cfg["params"].setdefault("buffer_mul",1.0)
          # ensure per-run
          runs=cfg.get("runs",{}) or {}
          for k,v in runs.items():
              if not isinstance(v,dict): 
                  continue
              v.setdefault("params",{})
              v["params"].setdefault("atr_pct", cfg["params"]["atr_pct"])
              v["params"].setdefault("buffer_mul", cfg["params"]["buffer_mul"])
          cfg["runs"]=runs
          with open(p,"w",encoding="utf-8") as f:
              yaml.safe_dump(cfg,f,sort_keys=False,allow_unicode=True)
          print("OK: injected params at top-level and per-run.")
          for k in runs.keys():
              print(" run",k,"params:",runs[k].get("params"))
          PY

      - name: Show config header (sanity)
        run: sed -n '1,120p' etf-trading-config/model.yaml

      - name: Run backtests (all runs in config)
        run: |
          python etf-trading-engine/scripts/run_ci_backtest.py             --config etf-trading-config/model.yaml             --data etf-trading-engine/data/eod.csv             --outdir outputs

      - name: Walk-Forward report (all runs)
        run: |
          python etf-trading-engine/scripts/walk_forward.py             --config etf-trading-config/model.yaml             --data etf-trading-engine/data/eod.csv             --windows etf-trading-config/wf_windows.yaml             --outdir outputs

      - name: Upload artifacts (all runs)
        uses: actions/upload-artifact@v4
        with:
          name: kpis-all-runs
          path: |
            outputs/**/kpis.json
            outputs/**/summary.txt
            outputs/**/equity_curve.csv
            outputs/**/wf_report.json
            outputs/**/wf_summary.txt
          if-no-files-found: warn
