name: Content Mirror
on:
  workflow_dispatch:
  schedule:
    - cron: "50 6 * * *"
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Mirror textual files
        run: |
          python etf-trading-engine/scripts/fetch_file.py \
            --repo ${{ github.repository }} \
            --ref ${{ github.ref_name }} \
            --patterns "**/*.md,**/*.yml,**/*.yaml,**/*.csv,**/*.json,**/*.py" \
            --outdir outputs/mirror
      - name: Upload mirror artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-mirror
          path: outputs/mirror
