name: EOD Dataset Publisher

on:
  workflow_dispatch: {}
  schedule:
    - cron: "15 4 * * *"  # 06:15 Europe/Rome

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: etf-trading-engine
    steps:
      - name: Checkout trading-suite
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r etf-trading-engine/requirements.txt

      - name: Download EOD (Web)
        run: |
          python etf-trading-engine/scripts/download_eod_yf.py             --universe ./etf-trading-config/universe.csv             --output ./etf-trading-engine/data/eod.csv             --start 2018-01-01             --threads 4             --sleep 0.25             --adjusted

      - name: Sanity check
        run: |
          python etf-trading-engine/scripts/sanity_check.py             --data ./etf-trading-engine/data/eod.csv             --min_rows 1000 --max_dd_allowed_pct 90

      - name: Build dataset (CSV+Parquet)
        run: |
          python etf-trading-engine/scripts/publish_dataset.py             --input ./etf-trading-engine/data/eod.csv             --outdir ./dataset

      - name: Upload dataset artifacts
        uses: actions/upload-artifact@v4
        with:
          name: eod-dataset
          path: |
            dataset/eod-latest.csv
            dataset/eod-latest.parquet
            dataset/by_ticker/*
            dataset/summary.json

      - name: Publish to datalake repo (latest/)
        env:
          GH_TOKEN: ${{ secrets.DATASINK_TOKEN }}
        run: |
          set -e
          git config --global user.name "ci-bot"
          git config --global user.email "ci-bot@users.noreply.github.com"
          rm -rf /tmp/datalake
          git clone https://x-access-token:${{ secrets.DATASINK_TOKEN }}@github.com/antoniosanso/etf-datalake.git /tmp/datalake
          mkdir -p /tmp/datalake/latest
          cp -f dataset/eod-latest.csv /tmp/datalake/latest/eod-latest.csv
          if [ -f dataset/eod-latest.parquet ]; then cp -f dataset/eod-latest.parquet /tmp/datalake/latest/eod-latest.parquet; fi
          cp -f dataset/summary.json /tmp/datalake/latest/summary.json
          git -C /tmp/datalake add -A
          git -C /tmp/datalake commit -m "Update dataset (from trading-suite $${GITHUB_SHA} )" || echo "No changes to commit"
          git -C /tmp/datalake push origin main
