name: Cleanup — Remove legacy EOD publisher
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove legacy EOD workflows and self-delete
        run: |
          set -e
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"

          removed=0
          for f in             ".github/workflows/build-and-publish.yml"             ".github/workflows/build-and-publish.yaml"             ".github/workflows/eod_dataset_publisher.yml"             ".github/workflows/eod_dataset_publisher.yaml"             ".github/workflows/eod_publisher.yml"             ".github/workflows/eod_publisher.yaml"             .github/workflows/EOD*.yml             .github/workflows/EOD*.yaml
          do
            if [ -f "$f" ]; then
              echo "Removing $f"
              git rm -f "$f" || true
              removed=1
            fi
          done

          # remove this cleanup workflow as well
          if [ -f ".github/workflows/remove_legacy_eod.yml" ]; then
            echo "Removing self workflow"
            git rm -f ".github/workflows/remove_legacy_eod.yml" || true
          fi

          if [ "$removed" -eq 1 ]; then
            git commit -m "chore: remove legacy EOD publisher workflows"
            git push origin HEAD:main
            echo "Legacy workflows removed and changes pushed."
          else
            echo "No legacy workflow files found. Nothing to do."
          fi
