name: Retro Run — As-Of

on:
  workflow_dispatch:
    inputs:
      as_of:
        description: "Data limite (YYYY-MM-DD)"
        required: true
        type: string
      start:
        description: "Data di inizio (opzionale, YYYY-MM-DD)"
        required: false
        type: string

concurrency:
  group: retro-asof-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  retro:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
      - name: Checkout suite
        uses: actions/checkout@v4

      - name: Checkout datalake (read-only)
        uses: actions/checkout@v4
        with:
          repository: antoniosanso/etf-datalake
          path: etf-datalake
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r etf-trading-engine/requirements.txt

      - name: Merge EOD dal datalake
        run: |
          python etf-trading-engine/scripts/merge_eod.py             --datalake ./etf-datalake             --output  ./etf-trading-engine/data/eod.csv             --recursive             --datecol dt --closecol close --tickercol ticker             --opencol open --highcol high --lowcol low --volumecol volume

      - name: Clip data to as-of
        run: |
          python etf-trading-engine/scripts/clip_asof.py             --input  ./etf-trading-engine/data/eod.csv             --output ./etf-trading-engine/data/eod_asof.csv             --as-of "${{ inputs.as_of }}"             ${{ inputs.start && format('--start {0}', inputs.start) }}
          mv ./etf-trading-engine/data/eod_asof.csv ./etf-trading-engine/data/eod.csv

      - name: Build features (as-of)
        run: |
          python etf-trading-engine/scripts/build_features.py             --features ./etf-trading-config/features.yaml             --universe ./etf-trading-config/universe.csv             --outdir ./features_asof

      - name: Generate signals (as-of)
        run: |
          python etf-trading-engine/scripts/signals.py             --config ./etf-trading-config/signals.yaml             --features_cfg ./etf-trading-config/features.yaml             --features_dir ./features_asof             --outdir ./outputs_asof

      - name: Backtest (as-of)
        run: |
          python etf-trading-engine/examples/run_backtest.py             --config ./etf-trading-config/model.yaml             --data   ./etf-trading-engine/data/eod.csv             --outdir ./outputs_asof

      - name: Walk-Forward (as-of)
        run: |
          python etf-trading-engine/scripts/walk_forward.py             --config ./etf-trading-config/model.yaml             --data   ./etf-trading-engine/data/eod.csv             --windows etf-trading-config/wf_windows.yaml             --outdir ./outputs_asof

      - name: Evaluate realized P&L vs expected & B&H + extra checks
        run: |
          python etf-trading-engine/scripts/guardrails.py             --config ./etf-trading-config/model.yaml             --kpis ./outputs_asof/kpis.json             --wf ./outputs_asof/wf_report.json || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: retro-asof-${{ inputs.as_of }}
          path: |
            outputs_asof/**
            etf-trading-engine/data/eod.csv
