name: Trading Suite — Unified Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "45 15 * * 1-5"

permissions:
  contents: read

jobs:
  unified:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout suite
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout datalake (read-only)
        uses: actions/checkout@v4
        with:
          repository: antoniosanso/etf-datalake
          path: etf-datalake
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install runtime deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyyaml numpy

      - name: Build/refresh universe (>=200 ETFs)
        run: |
          python etf-trading-engine/scripts/build_universe.py --min 220 --venues "Borsa Italiana,Euronext Paris,Euronext Amsterdam"

      - name: Merge EOD (auto-detect layout & columns)
        run: |
          python etf-trading-engine/scripts/merge_eod_robust.py             --datalake ./etf-datalake             --output   ./etf-trading-engine/data/eod.csv

      - name: Run model
        run: |
          mkdir -p outputs
          python etf-trading-engine/scripts/run_ci_backtest.py             --config ./etf-trading-config/model.yaml             --data   ./etf-trading-engine/data/eod.csv             --outdir ./outputs

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: unified-daily-results
          path: outputs/*
