name: Universe Snapshot
on:
  workflow_dispatch:
  schedule:
    - cron: "20 6 * * *"
jobs:
  fetch-universe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Fetch & validate universe
        run: |
          python etf-trading-engine/scripts/fetch_universe.py \
            --repo antoniosanso/etf-trading-suite \
            --path etf-trading-config/universe.csv \
            --outdir outputs/universe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: universe-snapshot
          path: |
            outputs/universe/universe_snapshot.csv
            outputs/universe/universe_snapshot.json
